#!/usr/bin/env python3
"""
Fetch a person's GitHub PR descriptions and review/issue comments into JSON.

Collects, for a given user across given orgs (or repos):
  - PR descriptions (bodies) of PRs they AUTHORED        -> descriptions.json
  - issue comments, review comments, and review bodies
    they wrote on PRs they COMMENTED on                  -> comments.json

Each record is tagged with `agent_authored` (best-effort) so the analysis step
can exclude content written by a coding agent on the person's behalf.

Why this script exists: GitHub's search endpoint rate-limits aggressively and a
naive burst of `gh api` calls trips a SECONDARY rate limit that silently fails.
This encodes the safe pattern: GET-only with query params in the path (never
`-f`, which flips to POST), exponential backoff on rate-limit responses,
serialized search calls, and low fetch concurrency.

Requires the `gh` CLI, authenticated for the target host
(`gh auth status`). Usage:

  python fetch_github.py --user LOGIN --orgs org1,org2 --out DIR \
      [--since 2025-01-01] [--until 2025-12-31] \
      [--repos owner/repo,owner/repo2] [--max-pages 3] [--hostname HOST]
"""
import argparse, json, os, subprocess, time, re
from concurrent.futures import ThreadPoolExecutor, as_completed

SHA = re.compile(r'\b[0-9a-f]{7,40}\b')
EXPLICIT_AGENT = [
    "🤖", "generated with [claude", "generated with claude code",
    "co-authored-by: claude", "co-authored-by: copilot", "generated by copilot",
    "claude.com/claude-code", "noreply@anthropic", "### code review",
]

def gh(path, hostname=None, tries=6):
    cmd = ["gh", "api", "-X", "GET"]
    if hostname:
        cmd += ["--hostname", hostname]
    cmd += [path]
    for attempt in range(tries):
        try:
            r = subprocess.run(cmd, capture_output=True, text=True, timeout=90)
        except Exception:
            time.sleep(5); continue
        if r.returncode == 0:
            try:
                return json.loads(r.stdout)
            except Exception:
                return None
        blob = (r.stderr + r.stdout).lower()
        if any(k in blob for k in ("secondary rate limit", "rate limit", "abuse")):
            time.sleep(min(180, 20 * (attempt + 1) ** 2))  # 20,80,180,...
            continue
        return None
    return None

def as_list(x):
    return x if isinstance(x, list) else []

def login_of(c):
    u = c.get("user") if isinstance(c, dict) else None
    return u.get("login") if isinstance(u, dict) else None

def in_range(ts, since, until):
    if not isinstance(ts, str):
        return False
    d = ts[:10]
    if since and d < since:
        return False
    if until and d > until:
        return False
    return True

def is_agent_comment(body):
    b = body or ""
    bl = b.lower()
    if any(m in bl for m in EXPLICIT_AGENT):
        return True
    has_sha = bool(SHA.search(b))
    if re.match(r"\s*(good catch|good point|great point|great catch|fair point|"
                r"nice catch|addressed in|fixed in|done in)\b", bl) and (has_sha or len(b) > 200):
        return True
    if "—" in b and has_sha:
        return True
    if has_sha and len(b) > 220:
        return True
    return False

def is_agent_description(title, body, branch):
    blob = f"{title}\n{body}\n{branch}".lower()
    if any(m in blob for m in EXPLICIT_AGENT):
        return True
    if re.search(r'#+\s*(problem & solution overview|test plan)\b', body or "", re.I) and "—" in (body or ""):
        return True
    return False

def build_query(role, user, scope, since, until):
    q = f"{role}:{user}+{scope}+type:pr"
    if since or until:
        q += f"+created:{since or '*'}..{until or '*'}"
    return q

def search_prs(user, scope, role, since, until, hostname, max_pages):
    prs = []
    for p in range(1, max_pages + 1):
        q = build_query(role, user, scope, since, until)
        data = gh(f"search/issues?q={q}&sort=created&order=asc&per_page=100&page={p}", hostname)
        time.sleep(3)  # serialize search calls; this endpoint throttles hard
        if not isinstance(data, dict):
            break
        items = as_list(data.get("items"))
        for it in items:
            url = it.get("repository_url", "")
            if "/repos/" in url:
                prs.append({"repo": url.split("/repos/")[1], "number": it.get("number")})
        if len(items) < 100:
            break
    return prs

def fetch_description(pr, hostname):
    d = gh(f"/repos/{pr['repo']}/pulls/{pr['number']}", hostname)
    if not isinstance(d, dict):
        return None
    title = d.get("title", "") or ""
    body = d.get("body") or ""
    branch = (d.get("head") or {}).get("ref", "")
    return {
        "repo": pr["repo"], "pr": pr["number"], "title": title, "body": body,
        "branch": branch, "created": d.get("created_at"),
        "agent_authored": is_agent_description(title, body, branch),
    }

def fetch_comments(pr, user, since, until, hostname):
    repo, num = pr["repo"], pr["number"]
    out = []
    def add(items, kind, tskey):
        for c in as_list(items):
            if login_of(c) == user and in_range(c.get(tskey), since, until):
                body = c.get("body", "") or ""
                if body.strip():
                    out.append({"repo": repo, "pr": num, "kind": kind, "body": body,
                                "created": c.get(tskey), "agent_authored": is_agent_comment(body)})
    add(gh(f"/repos/{repo}/issues/{num}/comments?per_page=100", hostname), "issue_comment", "created_at")
    time.sleep(0.15)
    add(gh(f"/repos/{repo}/pulls/{num}/comments?per_page=100", hostname), "review_comment", "created_at")
    time.sleep(0.15)
    add(gh(f"/repos/{repo}/pulls/{num}/reviews?per_page=100", hostname), "review_body", "submitted_at")
    return out

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--user", required=True, help="GitHub login")
    ap.add_argument("--orgs", default="", help="comma-separated orgs")
    ap.add_argument("--repos", default="", help="comma-separated owner/repo (instead of/with orgs)")
    ap.add_argument("--out", required=True, help="output dir")
    ap.add_argument("--since", default="", help="YYYY-MM-DD (PR creation date)")
    ap.add_argument("--until", default="", help="YYYY-MM-DD")
    ap.add_argument("--max-pages", type=int, default=3, help="search pages per scope (100/page)")
    ap.add_argument("--workers", type=int, default=4)
    ap.add_argument("--hostname", default="", help="GitHub Enterprise host, if not github.com")
    args = ap.parse_args()

    os.makedirs(args.out, exist_ok=True)
    host = args.hostname or None
    scopes = [f"org:{o.strip()}" for o in args.orgs.split(",") if o.strip()]
    scopes += [f"repo:{r.strip()}" for r in args.repos.split(",") if r.strip()]
    if not scopes:
        raise SystemExit("provide --orgs and/or --repos")

    # Authored PR descriptions
    authored = []
    for s in scopes:
        authored += search_prs(args.user, s, "author", args.since, args.until, host, args.max_pages)
    print(f"authored PRs: {len(authored)}", flush=True)
    descs = []
    with ThreadPoolExecutor(max_workers=args.workers) as ex:
        for f in as_completed([ex.submit(fetch_description, pr, host) for pr in authored]):
            try:
                r = f.result()
                if r:
                    descs.append(r)
            except Exception:
                pass
    json.dump(descs, open(os.path.join(args.out, "descriptions.json"), "w"), indent=1)
    print(f"descriptions: {len(descs)} ({sum(d['agent_authored'] for d in descs)} tagged agent)", flush=True)

    # Commented PR comments
    commented = []
    for s in scopes:
        commented += search_prs(args.user, s, "commenter", args.since, args.until, host, args.max_pages)
    print(f"commented-on PRs: {len(commented)}", flush=True)
    comments = []
    with ThreadPoolExecutor(max_workers=args.workers) as ex:
        futs = [ex.submit(fetch_comments, pr, args.user, args.since, args.until, host) for pr in commented]
        for i, f in enumerate(as_completed(futs)):
            try:
                comments.extend(f.result() or [])
            except Exception:
                pass
            if i % 40 == 0:
                print(f"  {i}/{len(futs)} -> {len(comments)} comments", flush=True)
    json.dump(comments, open(os.path.join(args.out, "comments.json"), "w"), indent=1)
    print(f"comments: {len(comments)} ({sum(c['agent_authored'] for c in comments)} tagged agent)", flush=True)
    print("DONE", flush=True)

if __name__ == "__main__":
    main()
